### ISSUE TITLE
You are not allowed to access this resource

### ISSUE THREAD

**Issue by Nega-ve** [AlexandreSenpai/Enma#47]
```
from NHentai import NHentai, CloudFlareSettings
nhentai_async = NHentai(request_settings=CloudFlareSettings(csrftoken="hne[...]", cf_clearance="1qDg[...]"))
print(nhentai_async.get_page(page=1))

```
Being locked out of the api even with the right cf cookies.  Error message " NHentai.core.handler.ApiError: You are not allowed to access this resource "

**Comment by AlexandreSenpai** [comment]
I'm closing this issue as the new version fixes it.
[Enma](https://pypi.org/project/Enma/) v2.0.2
