### ISSUE TITLE
Nhentai api doesnt reflect correct created_at updated_at values

### ISSUE THREAD

**Issue by Nega-ve** [AlexandreSenpai/Enma#53]
Manga class defaulting to current datetime

> enma.source_manager.set_source(source_name="nhentai")
> nh_source = cast(NHentai, enma.source_manager.source)
> nh_source.set_config(config=config)
> 
> doujin = enma.get(171558)
> print(doujin.updated_at)

**Comment by AlexandreSenpai** [comment]
Thanks for sharing the issue. I'm going to proceed with the fix

**Comment by AlexandreSenpai** [comment]
The new version is now available!
pip install Enma==2.2.0
