### ISSUE TITLE
Manga object returned by nhentai.py doesn't contain characters or parodies

### ISSUE THREAD

**Issue by Czevak** [AlexandreSenpai/Enma#62]
The Manga object doesn't contain character or parody variables and NHentai.get() doesn't parse them either. Can these be updated to fetch them?

**Comment by Macaroni-Biff** [comment]
I noticed that there is an active PR that addresses this issue. The PR has failed some checks, but if you're trying to get this implemented ASAP then you may be able to work off of that PR. Just note that it is NOT from the repo creator and has failed checks so it may not work "out of the box".

**Comment by AlexandreSenpai** [comment]
Hello guys.

Enma isnt a NHentai specific library. Actually its an agnostic scrapper so we cant make the Manga entity with specific keys to bring all the nhentai features. At the current dev version `2.3.0.alpha-5` Enma brings in genres prop all the nhentai tags except for parodies and characters cuz it doesnt make much sense to be there.

the alpha version can be installed using:

```sh
pip install -i https://test.pypi.org/simple/ enma==2.3.0a5
```

I want to release this version in this month.

Thanks for suggesting features and fixes. I'd love to read them, it helps to improve the lib much faster (〃￣︶￣)人(￣︶￣〃)

**Comment by AlexandreSenpai** [comment]
Hello! Enma version 2.3.0 has been released!

```sh
pip install enma==2.3.0
```
