### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by shjee-afridi** [AlexandreSenpai/Enma#64]
```  File "/home/reaper/Desktop/test.py", line 15, in <module>
    doujin = enma.random()
             ^^^^^^^^^^^^^
  File "/home/reaper/.local/lib/python3.11/site-packages/enma/infra/entrypoints/lib/__init__.py", line 80, in wrapper
    return callable(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reaper/.local/lib/python3.11/site-packages/enma/infra/entrypoints/lib/__init__.py", line 145, in random
    response = self.__random_use_case.execute() # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reaper/.local/lib/python3.11/site-packages/enma/application/use_cases/get_random.py", line 19, in execute
    result = self.__manga_repository.random()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/reaper/.local/lib/python3.11/site-packages/enma/infra/adapters/repositories/nhentai.py", line 312, in random
    id = cast(Tag, soup.find('h3', id='gallery_id')).text.replace('#', '')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'```

**Comment by AlexandreSenpai** [comment]
Thank you for the report @shjee-afridi. I'm going to fix this issue

**Comment by AlexandreSenpai** [comment]
@shjee-afridi  
This bug happened once or every .random call?
can you share with me your code block?

**Comment by shjee-afridi** [comment]
I just try to run the code snippet you provided in read me

`from typing import cast
from enma import Enma, DefaultAvailableSources, CloudFlareConfig, NHentai, Sort

enma = Enma[DefaultAvailableSources]()

config = CloudFlareConfig(
    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
    cf_clearance=''
)

enma.source_manager.set_source(source_name='nhentai')
nh_source = cast(NHentai, enma.source_manager.source)
nh_source.set_config(config=config)

doujin = enma.random()
print(doujin)`

**Comment by AlexandreSenpai** [comment]
Did you retrieve the cf_clearance from NHentai website?

**Comment by shjee-afridi** [comment]
I did not
Sorry my bad ill try again

**Comment by shjee-afridi** [comment]
it worked

**Comment by AlexandreSenpai** [comment]
Cool, i'm closing this issue. But i'm going to work to expose clearly this kind of errors on the next release.
Thanks for using and supporting Enma \(￣︶￣*\))

**Comment by shjee-afridi** [comment]
same error again
```    id = cast(Tag, soup.find('h3', id='gallery_id')).text.replace('#', '')
AttributeError: 'NoneType' object has no attribute 'text'```

```
from typing import cast
from enma import Enma, DefaultAvailableSources, CloudFlareConfig, NHentai, Sort

enma = Enma[DefaultAvailableSources]()

config = CloudFlareConfig(
    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
    cf_clearance='U59IPgDBmnusZw5WP9f4vNR6fn6zoE7Fe8UAu6yi4Qw-1708788071-1.0-AaGWJxPmBVhQcCnsoNByVuKxsakAszIqOEsIlUjP5eLDwUnk8bKa9kId4CEOnlsoS2l9+SeE2zHbcBXtVZJiPHk='
)

enma.source_manager.set_source(source_name='nhentai')
nh_source = cast(NHentai, enma.source_manager.source)
nh_source.set_config(config=config)

doujin = enma.random()
print(doujin)```

**Comment by AlexandreSenpai** [comment]
Hello, did you refreshed the cf_clearance? This token has an expiration time.

**Comment by shjee-afridi** [comment]
yes i did its fresh token you can try the token

**Comment by shjee-afridi** [comment]
![Uploading 2.png…]()

**Comment by shjee-afridi** [comment]
![2](https://github.com/AlexandreSenpai/Enma/assets/84635243/ea24d257-844d-4b9d-aeeb-9544b3e02962)

**Comment by AlexandreSenpai** [comment]
As you can, NHentai is blocking your token with 403 Forbidden

![image](https://github.com/AlexandreSenpai/Enma/assets/32408382/7fe9a4df-f7df-4675-91e6-c40df7b4011c)

You can check it out enabling enma logs doing as shown below

```python
from enma import Enma, CloudFlareConfig, LogMode, logger

enma = Enma()

logger.mode = LogMode.DEBUG

enma.source_manager.set_source(source_name='nhentai')
enma.source_manager.source.set_config(config=CloudFlareConfig(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
                                                              cf_clearance='U59IPgDBmnusZw5WP9f4vNR6fn6zoE7Fe8UAu6yi4Qw-1708788071-1.0-AaGWJxPmBVhQcCnsoNByVuKxsakAszIqOEsIlUjP5eLDwUnk8bKa9kId4CEOnlsoS2l9+SeE2zHbcBXtVZJiPHk='))

random_doujin = enma.random()
print(random_doujin)
```

Using the token that i just got from Nhentai Website it goes ok

![image](https://github.com/AlexandreSenpai/Enma/assets/32408382/e115bdc6-1af9-4585-b029-c4bdd270e557)
![image](https://github.com/AlexandreSenpai/Enma/assets/32408382/ab80e933-94d1-4703-9a6c-db38e8994578)

**Comment by AlexandreSenpai** [comment]
Try to perform a new login or access using another browser
