### ISSUE TITLE
nhentai's request ends up with 404 status code

### ISSUE THREAD

**Issue by IvanCMC37** [AlexandreSenpai/Enma#73]
Hi just want to check if the function for nhentai is working correctly at the moment or not, I have been getting 404 error since earlier this week as shown on attachment below:
<img width="309" alt="image" src="https://github.com/AlexandreSenpai/Enma/assets/26697952/166afd7d-b455-44f0-95cc-3b4cfd688df6">
I have also visited the nhentai api that enma is using manually and getting 404 error as well.
<img width="1459" alt="image" src="https://github.com/AlexandreSenpai/Enma/assets/26697952/cfc4b4d5-5a0f-48c3-87a9-95341d8afc79">
I wonder if that is something to do with my settings or any changes on nhentai api end?

**Comment by AlexandreSenpai** [comment]
Hello, @IvanCMC37 thank you very much for reporting it. 
I'm going to analyze NHentai source to see whats happening!

**Comment by AlexandreSenpai** [comment]
The problem was solved and the fix will be released today
