### ISSUE TITLE
First example in README is outdated

### ISSUE THREAD

**Issue by alexander-cummings** [AlexandreSenpai/Enma#75]
As mentioned in https://github.com/AlexandreSenpai/Enma/issues/55, the first example in the README that uses `DefaultAvailableSources` does not work with the current iteration of Enma. Please consider updating the example.

**Comment by AlexandreSenpai** [comment]
Hi Alexander, thanks for reporting it.
I'm going to update it! (〃￣︶￣)人(￣︶￣〃)

**Comment by AlexandreSenpai** [comment]
Fixed.

**Comment by alexander-cummings** [comment]
@AlexandreSenpai The import of `Sort` from `enma` in your update also appears to be invalid.

**Comment by AlexandreSenpai** [comment]
At version 2.4.1 it seems to be working well.

![image](https://github.com/AlexandreSenpai/Enma/assets/32408382/6b4174eb-7c5f-496a-ab2d-4b8c35041266)

Can you show me the specific error that youre facing so i can help you more precisely? (●'◡'●)

**Comment by AlexandreSenpai** [comment]
You're right!
I've updated the Enma documentation including a section about Sorting on `search` topic.
https://docs.minorin.io/enma/documentation/entrypoint-methods/search
