### ISSUE TITLE
Get Author, Parody, and Character

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [AlexandreSenpai/Enma#79]
What's the current sentiment on pulling these items from nHentai when specifying an ID? Currently trying to parse an ID database and would like to catalogue all the tags, not just Genre.

**Comment by AlexandreSenpai** [comment]
Hello @SakiSakiSakiSakiSaki. It going to be available in the next release. Thanks for waiting  (⁠.⁠ ⁠❛⁠ ⁠ᴗ⁠ ⁠❛⁠.⁠)

**Comment by SakiSakiSakiSakiSaki** [comment]
Hi @AlexandreSenpai, I see that you linked this issue to a PR. Are we now able to fetch author, parody, and character through the package now?

**Comment by AlexandreSenpai** [comment]
Hello @SakiSakiSakiSakiSaki 

Yes, you can access the doujin genres by `doujin.genres` and it tags by `doujin.tags`

![Image](https://github.com/user-attachments/assets/830fa077-46b0-4f26-aa25-953b0bfd131b)
![Image](https://github.com/user-attachments/assets/5012efe6-be2d-4042-937a-d4881b81eabd)
